name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '5 11 * * 1'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - run: npm run format-check

  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm clean-install
      - run: npm run test-types

  node-versions:
    name: Get Node.js Versions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.query.outputs.matrix }}
    steps:
      - id: query
        run: |
          echo "matrix=$(curl -s https://raw.githubusercontent.com/actions/node-versions/refs/heads/main/versions-manifest.json | jq -c '[.[] | select(.lts) | select(.version | split(".")[0] | tonumber >= 16) | .lts | ascii_downcase | "lts/\(.)"] + ["current"] | unique')" >> "$GITHUB_OUTPUT"

  test:
    runs-on: ubuntu-latest
    needs:
      - node-versions
    strategy:
      matrix:
        node-version: ${{ fromJSON(needs.node-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          check-latest: true
      - run: npm clean-install
      - run: npm run test
